### PR TITLE
Backwards timer for registrations closing

### PR DESCRIPTION
**Pull request by varun-balani**
I've implemented and tested the backwards timer for registrations closing. Testing has been done on Chrome for Windows. As for the dates for the opening and closing of the registrations, I've used the ones mentioned by Sambit during the last meeting. The timer only shows after registrations open, so for testing set your local time ahead.

### CODE REVIEW

**Review by r21meghashyam — APPROVED** [review]

**Comment by r21meghashyam** [comment]
@varun-balani 
Changes deployed to testing site, but not visible. Please check on this.

**Comment by varun-balani** [comment]
@r21meghashyam As I said before, it only shows after registrations open, starting 28th Feb. 
Displays fine after I set my phone  date to 28th. image

**Comment by r21meghashyam** [comment]
As per the document shared, the registration start date is  27th, has there been a change in the date?
Screenshot 2023-02-27 at 11 29 16 AM

**Comment by varun-balani** [comment]
27th Feb, 11:59 PM is the start date

**Comment by r21meghashyam** [comment]
Should have been from the beginning of the day, but it's fine now.

**Pull request merged**
